### ISSUE TITLE
PowerShell Cmdlet - Remove-CaasVlan

### ISSUE THREAD

**Issue by job-so** [DimensionDataCBUSydney/DimensionData.ComputeClient#1]
Hi Guys,
I am looking to a Cmdlet Remove-CaasVlan, like Remove-CaasNetwork to use against a MCP 2.0.
Thank you
Job.

**Comment by manishkp** [comment]
Thanks Job, adding Remove-CaasVlan and Remove-CaasNetworkDomain soon.
