### ISSUE TITLE
Get-CaasNetworkDomain Should have a parameter "Location" or "datacenterId" to specify which datacentre to search

### ISSUE THREAD

**Issue by riveryc** [DimensionDataCBUSydney/DimensionData.ComputeClient#15]
We can have Network Domains have same name in different datacenters.
When we search this name, it will return multiple result.
It's hard for user to locate a single object.

**Comment by manishkp** [comment]
Thanks River. List Network domain does support filtering by datacenterId , and the client library also supports it https://github.com/DimensionDataCBUSydney/DimensionData.ComputeClient/blob/master/ComputeClient/Compute.Contracts/Requests/Network20/NetworkDomainListOptions.cs 

It should'nt be hard to expose this in the powershell commandlet.
If you have spare time, can you try adding this ?

**Comment by riveryc** [comment]
#16 Added
