### ISSUE TITLE
Get-CaasNetworkDomain and New-CaasNetworkDomain, parameter should be consistent

### ISSUE THREAD

**Issue by riveryc** [DimensionDataCBUSydney/DimensionData.ComputeClient#17]
New-CaasNetworkDomain has "Location", which refers to Get-CaasNetworkDomain's "DatacenterId". 
I think we'd better keep one name as "DatacenterId" rather than "Location" as it's using "DatacenterId" in the web API. 

Any suggestion?
If you guys are all OK with this, I'll go ahead to change it in New-CaasNetworkDomain. 

Thanks
River

**Comment by riveryc** [comment]
I'll just create a new parameter called "DatacenterId" but not removing the "Location" as this will impact other users's code. We can mention this to be obsoleted in next or next few releases. 

Any suggestion?
River

**Comment by tonybaloney** [comment]
those aren't the only 2 commands that use that parameter. check the others too

**Comment by riveryc** [comment]
I'll also correct some class file name too... 
DeployCaasNetworkDomainCmdlet.cs = New-CaasNetworkDomain doesn't make sense.

Maybe just change it to NewCaasNetworkDomainCmdlet.cs. 

I'll take a look and change it when I see it.

**Comment by manishkp** [comment]
You can use Alias attribute with "Location" in it, so that it doesn't break backward compatibility

**Comment by riveryc** [comment]
Already done with merge #19
