### ISSUE TITLE
NetworkDomainId in VlanListOptions does not accept a valid GUID

### ISSUE THREAD

**Issue by phspies** [DimensionDataCBUSydney/DimensionData.ComputeClient#2]
When setting the NetworkDomainId to a value GUID, the operation throws an exception in the object.

NetworkDomainId = '_vlan_options.NetworkDomainId' threw an exception of type 'System.InvalidCastException'

![image](https://cloud.githubusercontent.com/assets/4684625/14721623/55a106de-07d5-11e6-8dce-fa88d797fadd.png)

**Comment by phspies** [comment]
@tonybaloney any update on this issue?

**Comment by tonybaloney** [comment]
@phspies how did you reach this error? where was `InvalidCastException` raised from?

**Comment by tonybaloney** [comment]
https://github.com/DimensionDataCBUSydney/DimensionData.ComputeClient/blame/master/ComputeClient/Compute.Contracts/Requests/Network20/VlanListOptions.cs#L62 @pascal-enz you're using GetFilter<T> with a type of a nullable Guid. The const value is a `string` type. Pretty sure that's a mistake. can you check it plase.

**Comment by tonybaloney** [comment]
@phspies if you want to raise a PR there is a contribution process!

**Comment by phspies** [comment]
@tonybaloney, you meaning I should provide patch myself? What is the contribution process?

**Comment by manishkp** [comment]
@phspies , @tonybaloney ,
fixed the issue in develop , development/v2.1 and in release/v2.1 branches.
