### ISSUE TITLE
Set-CaasServerState Cannot bind parameter 'Server'.

### ISSUE THREAD

**Issue by smartyl** [DimensionDataCBUSydney/DimensionData.ComputeClient#4]
Hi Team,
Not sure if this is the right place to post this but couldn't find anywhere else. The DD dev portal doesn't allow either. I am using the latest powershell module and having this issue to shutdown a server uisng it's name. I do understand that All commands expecting the -Server parameter must use the Get-CaasServer but can't figure out to pass that . Hoping that you could help.

command:
Set-CaasServerState -Action Shutdown -Server myservername

Error received: 
et-CaasServerState : Cannot bind parameter 'Server'. Cannot convert the myservername value of type
"System.String" to type "DD.CBU.Compute.Api.Contracts.Server.ServerWithBackupType".
At line:1 char:48
+   Set-CaasServerState -Action Shutdown -Server myservername
+                                                ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-CaasServerState], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,DD.CBU.Compute.Powershell.SetCaasServerActionCmdlet

**Comment by manishkp** [comment]
Thanks smartyl for reaching out.
You can pipe the server like below
Get-CaasServer -Name myservername | % {if($_ -ne $null) { $_ | Set-CaasServerState -Action PowerOn }}

or Assign it explicitly to Server parameter
Set-CaasServerState -Action PowerOn -Server (Get-CaasServer -Name myservername)

Hope this helps.
Let us know if you need more help.
Thanks
Manish

**Comment by smartyl** [comment]
Thanks Manish for the Super Quick Response. I am trying to build a script to check if a server from a supplied list is Turned ON in a particular network then switch it OFF. This is what i have come up with but need to find a way to check the current status and confirm the network. It would be great if you can show the way.
$ProdNetwork = Get-CaasNetworks | Where name -eq "myNetwork"
$serverNames = Get-Content -Path "C:\Scripts\CloudAPIServerShutdown\ShutdownServersList.txt"
 foreach ( $serverName in $serverName ) {
Write-Host Shutting down $serverName.name 
  Set-CaasServerState -Action PowerOff -Server (Get-CaasServer -Name $serverName)
Write-Host Shutdown Completed $serverName.name
}

**Comment by tonybaloney** [comment]
Hi @smartyl 

I would probably write a script like this:

```powershell
$existing = (Get-Content "my_servers.json") -Join "`n" | ConvertFrom-Json
$network = Get-CaaSNetworks -Name "myNetwork" | Select-Object -First 1
$servers = Get-CaasServers -Network $prodNetwork
foreach ($server in $servers){
   Write-Host "Server ${$server}"
   // compare to whats in $existing 
   $oldServer = $existing | where $_.name -eq $server.name
   if (-Not $existing){
      // probably  a new server- don't care?
   } else {
      // check the 2
      if ($oldServer.state -ne $server.state){
         // state has changed, might have gone on to off, etc..
         Set-CaasServerState -Action PowerOff -Server $server
      } 
   }
}
$servers | ConvertTo-Json | Out-File "my_servers.json"
```

**Comment by smartyl** [comment]
Thanks Tony for your prompt response. I only want to TURN OFF servers if they are TURNED ON for the specified list. I am confused with this line if ($oldServer.state -ne $server.state). Secondly, in your script the list of servers has to be specified in my_servers.json file..is that correct ?

**Comment by tonybaloney** [comment]
oh ok, sorry I misunderstood. I though you meant you wanted to detect the servers that had changed state (so that example would save them in a file so you could compare them).

This should work.
```powershell
$existing = (Get-Content "my_servers.json") -Join "`n" | ConvertFrom-Json
$network = Get-CaaSNetworks -Name "myNetwork" | Select-Object -First 1
$servers = Get-CaasServers -Network $prodNetwork
foreach ($server in $servers){
   Write-Host "Server ${$server}"
   if ($server.state -ne "RUNNING" ){
      Set-CaasServerState -Action PowerOff -Server $server 
   }
}
```

**Comment by smartyl** [comment]
Thanks Tony. I get it now. I actually have a list of servernames in the .txt file so was thinking if could use that simple list instead of json. Basically, i just need to turn off servers that are in that list and are running.
$serverNames = Get-Content -Path "C:\Scripts\CloudAPIServerShutdown\ShutdownServersList.txt"

**Comment by c-mckenzie** [comment]
There are a lot of ways to achieve the same result but I think this might be what you are after

```
$ProdNetwork = Get-CaasNetwork -Name "MyNetwork"
$serverNames = Get-Content -Path "C:\Scripts\CloudAPIServerShutdown\ShutdownServersList.txt"

foreach ($Server in $ServerNames) {
    
    $CloudServer = Get-CaasServer -Network $ProdNetwork -Name $Server
    
        if ($CloudServer.started -eq $true -and $CloudServer.state -eq "NORMAL"){

            if ($CloudServer.vmwareTools.runningStatus -eq "RUNNING"){
                Write-Host Shutting down $Server  -ForegroundColor Yellow
                Set-CaasServerState -Action Shutdown -Server $CloudServer
            } else {
                Write-Host Forcing Shutdown of $Server  -ForegroundColor Red
                Set-CaasServerState -Action PowerOff -Server $CloudServer
            }
            
        }

}
```

**Comment by smartyl** [comment]
Thanks. Matches with what i wrote up.
$ProdNetwork = Get-CaaSNetworks -Name "myNetwork" | Select-Object -First 1
$serverNames = Get-Content -Path "C:\Scripts\CloudAPIServerShutdown\ShutdownServersList.txt"
foreach ( $serverName in $serverNames ) {
$server = Get-CaasServers -Name $serverName -Network $prodNetwork
if ($server.started -eq "True" ){
Write-Output "$serverName is running"
Set-CaasServerState -Action PowerOff -Server $server 
 Write-Output "$serverName has been shutdown"
 }
else
{
 Write-Output $serverName "is Not Running"
}
}
Remove-CaasConnection -Name "Connection"
Write-Output "Connection Closed"
